### ISSUE TITLE
Ability to Set Default Language (defaultLang) in Console Command

### ISSUE THREAD

**Issue by deonoize** [serkansyalcin/translation-checker#2]
Hello. I would like to propose to add the ability to set the default language (defaultLang) in the console command via the parameter

`php artisan lang:check-missing --default=ru`

**Comment by serkansyalcin** [comment]
@deonoize 
Hi, so what do you think will change with this method?

**Comment by deonoize** [comment]
To change this variable

https://github.com/serkansyalcin/translation-checker/blob/faaf1127682506c8e93043da39ad078921f3531e/src/Console/Commands/CheckMissingTranslations.php#L16

**Comment by serkansyalcin** [comment]
@deonoize 
Ok. I'll add that shortly. Thanks for the suggestion.

**Comment by deonoize** [comment]
@serkansyalcin 
This is still not :(

**Comment by serkansyalcin** [comment]
@deonoize 
Hi.
php artisan lang:check-missing --default=fr 
I made the necessary edits. Now you can add the country code to the parameter by default. Thanks.
